Improved VPN script

diff --git a/bin/bin/vpn b/bin/bin/vpn
--- a/bin/bin/vpn
+++ b/bin/bin/vpn
@@ -7,13 +7,13 @@
 # sudo nmcli connection modify wg0 autoconnect no
 # sudo nmcli connection down wg0
 #
-# Then: vpn [start|stop|status]
-# 
+# Then: vpn [-i interface] [start|stop|status]
+#
 
 IFACE=wg0
 
 function print_usage() {
-	echo "Usage: $(basename "$0") [start|stop|status]"
+	echo "Usage: $(basename "$0") [-i interface] [start|stop|status]"
 }
 
 function print_green() {
@@ -25,10 +25,22 @@ function print_red() {
 }
 
 
-if [ $# -ne 1 ]; then
+if [[ $# -lt 1 ]]; then
 	echo "Invalid number of parameters"
 	print_usage
 	exit 1
+fi
+
+# Get interface/profile name if present
+if [[ $# -gt 1 ]]; then
+	if [[ $# -eq 3 && "$1" == "-i" ]]; then
+		IFACE="$2"
+		shift 2
+	else
+		echo "Invalid argument: $1"
+		print_usage
+		exit 1
+	fi
 fi
 
 case "$1" in
@@ -46,7 +58,7 @@ case "$1" in
 	        fi
 		;;
 	*)
-		echo "Invalid parameter: $1"
+		echo "Invalid argument: $1"
 		print_usage
 		exit 1
 		;;
